config.puerto.servidor=8080
otra=algun valor
config.texto.ambiente=Este es un texto de ejemplo para el ambiente de desarrollo
config.autor.nombre= Lucia Hdez Pestana
config.autor.email=lucia@correo.com
